### ISSUE TITLE
Getting an Error while starting server

### ISSUE THREAD

**Issue by ravish0007** [BePsvPT/remote-browser#3]
```
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module '/home/ravish_nfs/remote-browser/.yarn/releases/yarn-berry.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by ravish0007** [comment]
fixed it by, following this process (https://github.com/yarnpkg/yarn/issues/8460#issuecomment-729565545)

Now it says...

```
Usage Error: The project in /home/ravish_nfs/remote-browser/package.json doesn't seem to have been installed - running an install
 there might help
```

**Comment by ravish0007** [comment]
Had to remove "yarn.lock" to over come above error.

Facing this.

```
Internal Error: @bepsvpt/remote-browser@workspace:.: This package doesn't seem to be present in your lockfile; try to make an ins
tall to update your resolutions
    at t.RunInstallPleaseResolver.getCandidates (/home/ravish_nfs/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/bin/yarn.js:3
6:863677)
    at t.MultiResolver.getCandidates (/home/ravish_nfs/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/bin/yarn.js:24:41320)
    at /home/ravish_nfs/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/bin/yarn.js:36:581640
    at /home/ravish_nfs/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/bin/yarn.js:36:857805
    at new Promise (<anonymous>)
    at e.exports (/home/ravish_nfs/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/bin/yarn.js:36:857787)
    at i (/home/ravish_nfs/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/bin/yarn.js:24:91764)
    at /home/ravish_nfs/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/bin/yarn.js:24:91837
    at /home/ravish_nfs/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/bin/yarn.js:24:91880
    at new Promise (<anonymous>)
```

**Comment by ravish0007** [comment]
yarn install 

did the job
